---
- name: Install and enable EPEL
  yum:
    name: epel-release
  when: centos_base_enable_epel|bool

- name: Install basic packages
  yum:
    name:
      - git
      - gcc
      - python-virtualenv
      - yum-cron
      - bzip2
      - vim-enhanced
      - screen
      - tree
      - wget
  when: centos_base_basic_packages|bool

- name: Install debugging packages
  yum:
    name:
      - strace
      - mtr
      - traceroute
      - nmap
      - iotop
      - vnstat
      - sysstat
      - net-tools
  when: centos_base_debug_packages|bool

- name: Install packages specific to CentOS 7
  yum:
    name:
      - fail2ban-all
      - python-inotify
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_enable_epel|bool
    - centos_base_fail2ban_configuration|bool

- name: Install firewalld
  yum:
    name: firewalld
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_security_packages|bool
    - centos_base_firewalld|bool

- name: Ensure fail2ban service is enabled and started
  service:
    name: fail2ban
    state: started
    enabled: true
  when: centos_base_fail2ban_configuration|bool

# Allow user to control /etc/fail2ban/jail.local
- name: Secure Fail2ban configuration
  template:
    src: etc/fail2ban/jail.d/centos_base.conf
    dest: /etc/fail2ban/jail.d
  when: centos_base_fail2ban_configuration|bool

- name: Secure SSH configuration
  template:
    src: etc/ssh/sshd_config
    dest: /etc/ssh
  notify: sshd restart
  when: centos_base_secure_sshd|bool

- name: Ensure firewalld is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: true
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_basic_packages|bool
    - centos_base_firewalld|bool

- name: Enable firewalld services
  firewalld:
    permanent: true
    service: "{{ item }}"
    state: enabled
    zone: public
  loop: "{{ centos_base_firewalld_services }}"
  notify:
    - firewalld restart
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    - centos_base_firewalld_services|length > 0
    - centos_base_firewalld|bool
